server:
  port: 0

spring:

  application:
    name: payment-service

  cloud:

    stream:

      default:
        binder: kafka

      function:
        definition: notification

      bindings:
        notification-out-0:
          destination: notification

      kafka:
        binder:
          brokers: 127.0.0.1:9092

    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s


resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 1
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 10
      eventConsumerBufferSize: 10


management.tracing.sampling.probability: 1.0

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"