server:
  port: 4040

spring:

  application:
    name: config-service

  profiles:
    active: native

  security:
    user:
      name: config-user
      password: config-pass

  cloud:

    config:
      server:
        native:
          search-locations: "classpath:/config"

    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        healthCheckPath: /actuator/health
        health-check-headers:
          # base64 ${spring.security.user.name}:${spring.security.user.password}
          Authorization: "Basic Y29uZmlnLXVzZXI6Y29uZmlnLXBhc3M="
        healthCheckInterval: 5s