server:
  port: 0

spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: merchant-service

  cloud:

    stream:
      function:
        definition: pkslowSink
      bindings:
        pkslowSink-in-0:
          destination: pkslow-topic
          group: test

    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
