server:
  port: 0

spring:

  application:
    name: notification-service

  cloud:

    stream:

      function:
        definition: notification

      bindings:
        notification-in-0:
          destination: notification
          group: notification-consumer

      kafka:
        binder:
          brokers: 127.0.0.1:9092

    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s